#!/usr/bin/env bash

current_path="${PWD}"

echo ""
echo "Installing on-my-zhs"

if [[ -e $HOME/.oh-my-zsh ]]; then
    echo "Oh-my zsh already exists" 
else
    git clone https://github.com/robbyrussell/oh-my-zsh.git "$HOME/.oh-my-zsh"     
fi

chsh -s `which zsh`

if [[ -e $HOME/.zshrc ]]; then
    rm  $HOME/.zshrc
fi
ln -s $current_path/zshrc $HOME/.zshrc

if [[ -e $HOME/.gemrc ]]; then
    rm  $HOME/.gemrc
fi
ln -s $current_path/gemrc $HOME/.gemrc

if [[ -e $HOME/.tmux.conf ]]; then
    rm  $HOME/.tmux.conf
fi
ln -s $current_path/tmux.conf $HOME/.tmux.conf

if [[ -e $HOME/.gitconfig ]]; then
    rm  $HOME/.gitconfig
fi
ln -s $current_path/gitconfig $HOME/.gitconfig

if [[ -e $HOME/.pryrc ]]; then
    rm  $HOME/.pryrc
fi
ln -s $current_path/pryrc $HOME/.pryrc


echo "done."
