#!/usr/bin/env bash

current_path="${PWD}"

echo ""
echo "Installing on-my-zhs"

if [[ -e $HOME/.oh-my-zsh ]]; then
    echo "Oh-my zsh already exists"
else
    git clone https://github.com/robbyrussell/oh-my-zsh.git "$HOME/.oh-my-zsh"
fi

sudo chsh -s `which zsh`

if [[ -e $HOME/.zshrc ]]; then
    rm  $HOME/.zshrc
fi
ln -s $current_path/zshrc $HOME/.zshrc

if [[ -e $HOME/.gemrc ]]; then
    rm  $HOME/.gemrc
fi
ln -s $current_path/gemrc $HOME/.gemrc

if [[ -e $HOME/.tmux.conf ]]; then
    rm  $HOME/.tmux.conf
fi
ln -s $current_path/tmux.conf $HOME/.tmux.conf

if [[ -e $HOME/.gitconfig ]]; then
    rm  $HOME/.gitconfig
fi
ln -s $current_path/gitconfig $HOME/.gitconfig

if [[ -e $HOME/.pryrc ]]; then
    rm  $HOME/.pryrc
fi
ln -s $current_path/pryrc $HOME/.pryrc

if [[ -e $HOME/.vuerc ]]; then
    rm  $HOME/.vuerc
fi
ln -s $current_path/vuerc $HOME/.vuerc

if [[ -e $HOME/.polipo ]]; then
    rm  $HOME/.polipo
fi
ln -s $current_path/polipo $HOME/.polipo

if [[ -e $HOME/.polipo-forbidden ]]; then
    rm  $HOME/.polipo-forbidden
fi
ln -s $current_path/polipo-forbidden $HOME/.polipo-forbidden

brew services start polipo
echo "See polipo config on http://127.0.0.1:1090/"

if [[ -e $HOME/.gradle/gradle.properties ]]; then
    rm  $HOME/.gradle/gradle.properties
fi
ln -s $current_path/gradle/gradle.properties $HOME/.gradle/gradle.properties

echo "done."
